name: Pull Request Checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Adding Clippy
      run: rustup component add clippy
    - name: Running Clippy
      run: cargo clippy -- -D warnings
    - name: Tests
      run: cargo test --verbose
