name: build-tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Tests
      run: cargo test --verbose
